# Generated by Django 3.1.4 on 2021-01-01 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('send_on', models.DateField(null=True)),
                ('content', django_cryptography.fields.encrypt(models.TextField())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_letter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
